# -*- coding: utf-8 -*-
"""score check.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XKRwkof6SdCeAWLWg9swX0a8sbpHKcL6
"""

from sklearn.ensemble import RandomForestRegressor

model1 = RandomForestRegressor(n_estimators=50,random_state=0)
model2 = RandomForestRegressor(n_estimators=100,random_state=0)
model3 = RandomForestRegressor(n_estimators=150,random_state=0,max_depth=6)
model4 = RandomForestRegressor(n_estimators=200,random_state=0,criterion='mae')

model = [model1,model2,model3,model4]

from sklearn.metrics import mean_absolute_error

# Function for comparing different models
def score_model(model, X_t=x_train, X_v=x_test, y_t=y_train, y_v=y_test):
    model.fit(X_t, y_t)
    preds = model.predict(X_v)
    return mean_absolute_error(y_v, preds)

for i in range(0, len(model)):
    mae = score_model(model[i])
    print("Model %d MAE: %d" % (i+1, mae))